@echo off
call conda create -n osdag-bleeding-env
call conda activate osdag-bleeding-env
call conda config --append channels conda-forge
call conda config --append channels dlr-sc
call conda install blas
call conda install sqlite
call conda install icc_rt
call conda install intel-openmp
call conda install mkl-service
call conda install mkl_fft
call conda install mkl_random
call conda install numpy
call conda install numpy-base
call conda install conda
call conda install certifi
call conda install mkl
call conda install openssl
call conda install ca-certificates
call conda install cairo
call conda install cairocffi
call conda install cairosvg
call conda install click
call conda install cssselect
call conda install defusedxml
call conda install freetype
call conda install gettext
call conda install glib
call conda install icu
call conda install jpeg
call conda install libblas
call conda install libcblas
call conda install libffi
call conda install libiconv
call conda install liblapack
call conda install libpng
call conda install libtiff
call conda install lz4-c
call conda install m2w64-gcc-libgfortran
call conda install m2w64-gcc-libs
call conda install m2w64-gcc-libs-core
call conda install m2w64-gmp
call conda install m2w64-libwinpthread-git
call conda install msys2-conda-epoch
call conda install olefile
call conda install pcre
call conda install pillow
call conda install pixman
call conda install pyparsing
call conda install python_abi
call conda install svgwrite
call conda install tinycss2
call conda install tk
call conda install webencodings
call conda install xz
call conda install zlib
call conda install zstd
call conda install gl2ps
call conda install freeimageplus
call conda install pyqt
call conda install pdfkit
call conda install PyYAML
call conda install openpyxl
call conda install Pygments
call conda install XlsxWriter
call conda install PyLaTeX
call conda install pdflatex
call conda install keyring
call conda install PyGithub
call conda install pandas
call conda install pythonocc-core
call conda install occt
call conda install smesh
call conda install tbb
exit
